import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "bn" | "en";

const translations = {
  // Navbar & Navigation
  "nav.home": { bn: "হোম", en: "Home" },
  "nav.products": { bn: "পণ্যসমূহ", en: "Products" },
  "nav.about": { bn: "আমাদের সম্পর্কে", en: "About Us" },
  "nav.contact": { bn: "যোগাযোগ", en: "Contact" },
  "nav.faq": { bn: "জিজ্ঞাসা", en: "FAQ" },
  "nav.login": { bn: "লগইন", en: "Login" },
  "nav.dashboard": { bn: "ড্যাশবোর্ড", en: "Dashboard" },
  "nav.cart": { bn: "কার্ট", en: "Cart" },
  "nav.profile": { bn: "প্রোফাইল", en: "Profile" },
  "nav.category": { bn: "ক্যাটেগরি", en: "Category" },

  // Categories
  "cat.shirts": { bn: "শার্ট", en: "Shirts" },
  "cat.trousers": { bn: "ট্রাউজার্স", en: "Trousers" },
  "cat.ethnic": { bn: "এথনিক পোশাক", en: "Ethnic Wear" },
  "cat.jackets": { bn: "জ্যাকেট ও ব্লেজার", en: "Jackets & Blazers" },
  "cat.accessories": { bn: "এক্সেসরিজ", en: "Accessories" },
  "cat.digital": { bn: "ডিজিটাল পণ্য", en: "Digital Products" },

  // Announcements
  "announce.free_shipping": { bn: "৳৯৯৯+ অর্ডারে বিনামূল্যে শিপিং", en: "Free shipping on orders ৳999+" },
  "announce.summer": { bn: "🔥 গ্রীষ্মকালীন কালেকশন ২০২৬ — এখন লাইভ!", en: "🔥 Summer Collection 2026 — Now Live!" },
  "announce.discount": { bn: "কোড SHAHEB20 ব্যবহার করে প্রথম অর্ডারে ২০% ছাড়", en: "Use code SHAHEB20 for 20% off your first order" },
  "announce.friday": { bn: "প্রতি শুক্রবার নতুন পণ্য — সাথে থাকুন!", en: "New arrivals every Friday — Stay tuned!" },
  "announce.premium": { bn: "💎 প্রিমিয়াম সদস্যরা আগে অ্যাক্সেস পান", en: "💎 Premium members get early access" },

  // Hero
  "hero.badge": { bn: "নতুন কালেকশন ২০২৬", en: "New Collection 2026" },
  "hero.title1": { bn: "আপনার", en: "Redefine Your" },
  "hero.style": { bn: "স্টাইল", en: "Style" },
  "hero.title2": { bn: "নতুনভাবে সাজান SHAHEB এর সাথে", en: "with SHAHEB" },
  "hero.desc": { bn: "প্রিমিয়াম পুরুষদের পোশাক ও এক্সক্লুসিভ ডিজিটাল কন্টেন্ট। মানসম্পন্ন ফ্যাশন, আসল কারুশিল্প, আপনার দোরগোড়ায়।", en: "Premium men's fashion & exclusive digital content. Quality fashion, real craftsmanship, at your doorstep." },
  "hero.browse": { bn: "পণ্য দেখুন", en: "Browse Products" },
  "hero.story": { bn: "আমাদের গল্প", en: "Our Story" },
  "hero.customers": { bn: "সন্তুষ্ট গ্রাহক", en: "Happy Customers" },
  "hero.products": { bn: "পণ্যসমূহ", en: "Products" },
  "hero.rating": { bn: "গড় রেটিং", en: "Avg Rating" },

  // Products page
  "products.title": { bn: "সকল পণ্য", en: "All Products" },
  "products.found": { bn: "টি পণ্য পাওয়া গেছে", en: "products found" },
  "products.search": { bn: "পণ্য অনুসন্ধান করুন...", en: "Search products..." },
  "products.sort.popular": { bn: "সবচেয়ে জনপ্রিয়", en: "Most Popular" },
  "products.sort.newest": { bn: "নতুনতম", en: "Newest First" },
  "products.sort.priceLow": { bn: "মূল্য: কম → বেশি", en: "Price: Low → High" },
  "products.sort.priceHigh": { bn: "মূল্য: বেশি → কম", en: "Price: High → Low" },
  "products.categories": { bn: "ক্যাটেগরি", en: "Categories" },
  "products.priceRange": { bn: "মূল্য সীমা", en: "Price Range" },
  "products.clearFilters": { bn: "সব ফিল্টার মুছুন", en: "Clear All Filters" },
  "products.noProducts": { bn: "কোন পণ্য পাওয়া যায়নি", en: "No products found" },
  "products.noProductsDesc": { bn: "ফিল্টার বা সার্চ পরিবর্তন করে দেখুন।", en: "Try adjusting your filters or search query." },
  "products.addToCart": { bn: "কার্টে যোগ করুন", en: "Add to Cart" },
  "products.addedToCart": { bn: "কার্টে যোগ হয়েছে!", en: "Added to cart!" },
  "products.addedToWishlist": { bn: "উইশলিস্টে যোগ হয়েছে!", en: "Added to wishlist!" },
  "products.quickView": { bn: "দ্রুত দেখুন", en: "Quick View" },
  "products.allCategories": { bn: "সকল ক্যাটেগরি", en: "All Categories" },
  "products.continueShopping": { bn: "কেনাকাটা চালিয়ে যান", en: "Continue Shopping" },

  // Product Detail
  "product.inStock": { bn: "স্টকে আছে", en: "In Stock" },
  "product.outOfStock": { bn: "স্টক শেষ", en: "Out of Stock" },
  "product.color": { bn: "রঙ", en: "Color" },
  "product.size": { bn: "সাইজ", en: "Size" },
  "product.quantity": { bn: "পরিমাণ", en: "Quantity" },
  "product.addToCart": { bn: "কার্টে যোগ করুন", en: "Add to Cart" },
  "product.buyNow": { bn: "এখনই কিনুন", en: "Buy Now" },
  "product.selectSize": { bn: "সাইজ নির্বাচন করুন", en: "Please select a size" },
  "product.description": { bn: "বিবরণ", en: "Description" },
  "product.related": { bn: "আপনার পছন্দ হতে পারে", en: "You May Also Like" },
  "product.notFound": { bn: "পণ্য পাওয়া যায়নি", en: "Product Not Found" },
  "product.notFoundDesc": { bn: "আপনার খোঁজা পণ্যটি বিদ্যমান নেই বা সরিয়ে ফেলা হয়েছে।", en: "The product you're looking for doesn't exist or has been removed." },
  "product.freeDelivery": { bn: "ফ্রি ডেলিভারি", en: "Free Delivery" },
  "product.ordersAbove": { bn: "৳৯৯৯+ অর্ডারে", en: "Orders ৳999+" },
  "product.genuine": { bn: "আসল পণ্য", en: "Genuine Product" },
  "product.authentic": { bn: "১০০% অথেনটিক", en: "100% Authentic" },
  "product.easyReturns": { bn: "সহজ রিটার্ন", en: "Easy Returns" },
  "product.returnDays": { bn: "১৫ দিন", en: "15 Days" },
  "product.linkCopied": { bn: "লিঙ্ক কপি হয়েছে!", en: "Link copied to clipboard!" },
  "product.save": { bn: "সেভ", en: "Save" },

  // Cart
  "cart.title": { bn: "শপিং কার্ট", en: "Shopping Cart" },
  "cart.empty": { bn: "আপনার কার্ট খালি", en: "Your cart is empty" },
  "cart.emptyDesc": { bn: "এখনো কিছু যোগ করেননি। আমাদের কালেকশন ঘুরে দেখুন!", en: "Looks like you haven't added anything yet. Start exploring our collection!" },
  "cart.items": { bn: "টি আইটেম", en: "items" },
  "cart.total": { bn: "মোট", en: "total" },
  "cart.addMore": { bn: "আরো যোগ করুন", en: "Add more for free shipping" },
  "cart.freeShipping": { bn: "আপনি ফ্রি শিপিং পাচ্ছেন!", en: "You qualify for free shipping!" },
  "cart.orderSummary": { bn: "অর্ডার সারাংশ", en: "Order Summary" },
  "cart.subtotal": { bn: "সাবটোটাল", en: "Subtotal" },
  "cart.couponDiscount": { bn: "কুপন ছাড়", en: "Coupon Discount" },
  "cart.shipping": { bn: "শিপিং", en: "Shipping" },
  "cart.free": { bn: "ফ্রি", en: "Free" },
  "cart.proceedToCheckout": { bn: "চেকআউটে যান", en: "Proceed to Checkout" },
  "cart.secureCheckout": { bn: "সিকিউর চেকআউট", en: "Secure Checkout" },
  "cart.returns": { bn: "১৫-দিনের রিটার্ন", en: "15-Day Returns" },
  "cart.enterCoupon": { bn: "কুপন কোড লিখুন", en: "Enter coupon code" },
  "cart.apply": { bn: "প্রয়োগ", en: "Apply" },
  "cart.removed": { bn: "কার্ট থেকে সরানো হয়েছে", en: "Item removed from cart" },
  "cart.invalidCoupon": { bn: "অবৈধ কুপন কোড", en: "Invalid coupon code" },
  "cart.minOrder": { bn: "ন্যূনতম অর্ডার প্রয়োজন", en: "Minimum order required" },
  "cart.couponApplied": { bn: "কুপন প্রয়োগ হয়েছে!", en: "Coupon applied!" },
  "cart.discount": { bn: "ছাড়", en: "discount" },

  // Checkout
  "checkout.title": { bn: "চেকআউট", en: "Checkout" },
  "checkout.step.shipping": { bn: "শিপিং", en: "Shipping" },
  "checkout.step.payment": { bn: "পেমেন্ট", en: "Payment" },
  "checkout.step.review": { bn: "রিভিউ", en: "Review" },
  "checkout.shippingAddress": { bn: "শিপিং ঠিকানা", en: "Shipping Address" },
  "checkout.firstName": { bn: "নাম *", en: "First Name *" },
  "checkout.lastName": { bn: "পদবি", en: "Last Name" },
  "checkout.email": { bn: "ইমেইল", en: "Email" },
  "checkout.address": { bn: "ঠিকানা *", en: "Address *" },
  "checkout.city": { bn: "শহর *", en: "City *" },
  "checkout.postalCode": { bn: "পোস্ট কোড *", en: "Postal Code *" },
  "checkout.state": { bn: "বিভাগ *", en: "State/Division *" },
  "checkout.phone": { bn: "ফোন *", en: "Phone *" },
  "checkout.backToCart": { bn: "কার্টে ফিরে যান", en: "Back to Cart" },
  "checkout.continueToPayment": { bn: "পেমেন্টে যান", en: "Continue to Payment" },
  "checkout.paymentMethod": { bn: "পেমেন্ট পদ্ধতি", en: "Payment Method" },
  "checkout.bkash": { bn: "বিকাশ", en: "bKash" },
  "checkout.bkashDesc": { bn: "বিকাশ মোবাইল পেমেন্ট", en: "bKash mobile payment" },
  "checkout.nagad": { bn: "নগদ", en: "Nagad" },
  "checkout.nagadDesc": { bn: "নগদ মোবাইল পেমেন্ট", en: "Nagad mobile payment" },
  "checkout.cod": { bn: "ক্যাশ অন ডেলিভারি", en: "Cash on Delivery" },
  "checkout.codDesc": { bn: "পণ্য পেয়ে পেমেন্ট করুন", en: "Pay when you receive" },
  "checkout.card": { bn: "কার্ড পেমেন্ট", en: "Credit / Debit Card" },
  "checkout.cardDesc": { bn: "ভিসা, মাস্টারকার্ড", en: "Visa, Mastercard" },
  "checkout.back": { bn: "পিছনে", en: "Back" },
  "checkout.reviewOrder": { bn: "অর্ডার রিভিউ", en: "Review Order" },
  "checkout.edit": { bn: "সম্পাদনা", en: "Edit" },
  "checkout.payment": { bn: "পেমেন্ট", en: "Payment" },
  "checkout.items": { bn: "আইটেমসমূহ", en: "Items" },
  "checkout.estimatedDelivery": { bn: "আনুমানিক ডেলিভারি: ৩-৫ কার্যদিবস", en: "Estimated delivery: 3-5 business days" },
  "checkout.standardShipping": { bn: "স্ট্যান্ডার্ড শিপিং", en: "Standard shipping" },
  "checkout.placeOrder": { bn: "অর্ডার দিন", en: "Place Order" },
  "checkout.placingOrder": { bn: "অর্ডার হচ্ছে...", en: "Placing Order..." },
  "checkout.orderConfirmed": { bn: "অর্ডার নিশ্চিত হয়েছে!", en: "Order Confirmed!" },
  "checkout.orderSuccess": { bn: "আপনার অর্ডার সফলভাবে প্লেস করা হয়েছে।", en: "Your order has been placed successfully." },
  "checkout.orderId": { bn: "অর্ডার আইডি", en: "Order ID" },
  "checkout.viewOrders": { bn: "অর্ডার দেখুন", en: "View Orders" },
  "checkout.bkashNumber": { bn: "বিকাশ নম্বর", en: "bKash Number" },
  "checkout.nagadNumber": { bn: "নগদ নম্বর", en: "Nagad Number" },
  "checkout.trxId": { bn: "ট্রানজেকশন আইডি", en: "Transaction ID" },
  "checkout.paymentInstructions.bkash": { bn: "০১XXXXXXXXX নম্বরে বিকাশ করুন এবং ট্রানজেকশন আইডি দিন", en: "Send bKash to 01XXXXXXXXX and provide the transaction ID" },
  "checkout.paymentInstructions.nagad": { bn: "০১XXXXXXXXX নম্বরে নগদ করুন এবং ট্রানজেকশন আইডি দিন", en: "Send Nagad to 01XXXXXXXXX and provide the transaction ID" },
  "checkout.orderPlacedSuccess": { bn: "🎉 অর্ডার সফলভাবে দেওয়া হয়েছে!", en: "🎉 Order Placed Successfully!" },
  "checkout.orderConfirmedDesc": { bn: "অর্ডার নিশ্চিত হয়েছে।", en: "Order confirmed." },
  "checkout.orderFailed": { bn: "অর্ডার ব্যর্থ হয়েছে", en: "Failed to place order" },
  "checkout.orderFailedDesc": { bn: "আবার চেষ্টা করুন অথবা আগে লগইন করুন।", en: "Please try again or log in first." },
  "checkout.ssl": { bn: "২৫৬-বিট SSL এনক্রিপ্টেড · ১০০% নিরাপদ", en: "256-bit SSL encrypted · 100% secure" },
  "checkout.emptyCart": { bn: "আপনার কার্ট খালি", en: "Your cart is empty" },
  "checkout.browseProducts": { bn: "পণ্য দেখুন", en: "Browse Products" },
  "checkout.fillField": { bn: "পূরণ করুন", en: "Please fill in" },

  // Footer
  "footer.desc": { bn: "প্রিমিয়াম পুরুষদের ফ্যাশন ও ডিজিটাল কন্টেন্ট। আধুনিক ভদ্রলোকদের জন্য মানসম্পন্ন ও স্টাইলিশ পণ্য।", en: "Premium men's fashion & digital content. Quality & stylish products for the modern gentleman." },
  "footer.shop": { bn: "কেনাকাটা", en: "Shop" },
  "footer.allProducts": { bn: "সকল পণ্য", en: "All Products" },
  "footer.help": { bn: "সাহায্য", en: "Help" },
  "footer.contact": { bn: "যোগাযোগ", en: "Contact" },
  "footer.faq": { bn: "সাধারণ জিজ্ঞাসা", en: "FAQ" },
  "footer.trackOrder": { bn: "অর্ডার ট্র্যাক", en: "Track Order" },
  "footer.aboutUs": { bn: "আমাদের সম্পর্কে", en: "About Us" },
  "footer.contactInfo": { bn: "যোগাযোগ", en: "Contact" },
  "footer.rights": { bn: "সর্বস্বত্ব সংরক্ষিত।", en: "All rights reserved." },
  "footer.privacy": { bn: "গোপনীয়তা নীতি", en: "Privacy Policy" },
  "footer.terms": { bn: "শর্তাবলী", en: "Terms & Conditions" },
  "footer.refund": { bn: "রিফান্ড নীতি", en: "Refund Policy" },

  // Bottom Nav
  "bottom.home": { bn: "হোম", en: "Home" },
  "bottom.products": { bn: "পণ্য", en: "Products" },
  "bottom.cart": { bn: "কার্ট", en: "Cart" },
  "bottom.profile": { bn: "প্রোফাইল", en: "Profile" },

  // Auth
  "auth.login": { bn: "লগইন", en: "Login" },
  "auth.signup": { bn: "অ্যাকাউন্ট তৈরি", en: "Sign Up" },
  "auth.email": { bn: "ইমেইল ঠিকানা", en: "Email Address" },
  "auth.password": { bn: "পাসওয়ার্ড", en: "Password" },
  "auth.name": { bn: "পুরো নাম", en: "Full Name" },
  "auth.forgotPassword": { bn: "পাসওয়ার্ড ভুলে গেছেন?", en: "Forgot Password?" },
  "auth.noAccount": { bn: "অ্যাকাউন্ট নেই?", en: "Don't have an account?" },
  "auth.hasAccount": { bn: "ইতিমধ্যে অ্যাকাউন্ট আছে?", en: "Already have an account?" },
  "auth.resetPassword": { bn: "পাসওয়ার্ড রিসেট করুন", en: "Reset Password" },
  "auth.resetDesc": { bn: "আপনার ইমেইল দিন এবং আমরা একটি রিসেট লিঙ্ক পাঠাব।", en: "Enter your email and we'll send you a reset link." },
  "auth.sendResetLink": { bn: "রিসেট লিঙ্ক পাঠান", en: "Send Reset Link" },
  "auth.fillAll": { bn: "সব তথ্য পূরণ করুন", en: "Please fill in all fields" },
  "auth.loginFailed": { bn: "লগইন ব্যর্থ হয়েছে", en: "Login failed" },
  "auth.loginSuccess": { bn: "সফলভাবে লগইন হয়েছে!", en: "Logged in successfully!" },
  "auth.loginBenefitsDesc": { bn: "আপনার স্টাইল গন্তব্যে ফিরে আসুন। অর্ডার, উইশলিস্ট এবং এক্সক্লুসিভ সদস্য সুবিধা পেতে সাইন ইন করুন।", en: "Welcome back to your style destination. Sign in to access orders, wishlist and exclusive member benefits." },
  "auth.benefit1": { bn: "এক্সক্লুসিভ সদস্য-শুধু অফার", en: "Exclusive member-only offers" },
  "auth.benefit2": { bn: "রিয়েল-টাইমে অর্ডার ট্র্যাক করুন", en: "Track orders in real-time" },
  "auth.benefit3": { bn: "উইশলিস্টে আইটেম সংরক্ষণ করুন", en: "Save items to wishlist" },
  "auth.benefit4": { bn: "সেভ করা ঠিকানায় দ্রুত চেকআউট", en: "Quick checkout with saved addresses" },
  "auth.welcomeBack": { bn: "স্বাগতম", en: "Welcome Back" },
  "auth.loginSubtitle": { bn: "আপনার SHAHEB অ্যাকাউন্টে সাইন ইন করুন", en: "Sign in to your SHAHEB account" },
  "auth.enterPassword": { bn: "আপনার পাসওয়ার্ড দিন", en: "Enter your password" },
  "auth.rememberMe": { bn: "আমাকে মনে রাখুন", en: "Remember me" },
  "auth.signingIn": { bn: "সাইন ইন হচ্ছে...", en: "Signing in..." },
  "auth.signIn": { bn: "সাইন ইন", en: "Sign In" },
  "auth.sslSecure": { bn: "২৫৬-বিট SSL এনক্রিপশন দ্বারা সুরক্ষিত", en: "Secured with 256-bit SSL encryption" },
  "auth.passwordTooShort": { bn: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে", en: "Password must be at least 6 characters" },
  "auth.signupFailed": { bn: "অ্যাকাউন্ট তৈরি ব্যর্থ", en: "Sign up failed" },
  "auth.signupSuccess": { bn: "অ্যাকাউন্ট তৈরি হয়েছে!", en: "Account created!" },
  "auth.checkEmail": { bn: "ইমেইল যাচাই করতে আপনার ইনবক্স চেক করুন।", en: "Check your inbox to verify your email." },
  "auth.createAccount": { bn: "অ্যাকাউন্ট তৈরি করুন", en: "Create Account" },
  "auth.joinCommunity": { bn: "SHAHEB কমিউনিটিতে যোগ দিন", en: "Join the SHAHEB community" },
  "auth.fullNamePlaceholder": { bn: "আপনার পুরো নাম", en: "Your full name" },
  "auth.phone": { bn: "ফোন নম্বর", en: "Phone Number" },
  "auth.minChars": { bn: "কমপক্ষে ৬ অক্ষর", en: "At least 6 characters" },
  "auth.creatingAccount": { bn: "তৈরি হচ্ছে...", en: "Creating..." },
  "auth.termsAgree": { bn: "সাইন আপ করে আপনি আমাদের সেবার শর্তাবলী ও গোপনীয়তা নীতিতে সম্মত হচ্ছেন।", en: "By signing up, you agree to our Terms of Service and Privacy Policy." },
  "auth.resetFailed": { bn: "রিসেট ব্যর্থ হয়েছে", en: "Reset failed" },
  "auth.resetSent": { bn: "রিসেট লিঙ্ক পাঠানো হয়েছে! আপনার ইনবক্স চেক করুন।", en: "Reset link sent! Check your inbox." },
  "auth.logout": { bn: "লগআউট", en: "Logout" },
  "auth.myAccount": { bn: "আমার অ্যাকাউন্ট", en: "My Account" },

  // Search
  "search.title": { bn: "অনুসন্ধান", en: "Search" },
  "search.desc": { bn: "পণ্য, ক্যাটেগরি এবং আরো অনেক কিছু খুঁজুন", en: "Search products, categories and more" },
  "search.placeholder": { bn: "পণ্য অনুসন্ধান করুন...", en: "Search products..." },
  "search.popular": { bn: "জনপ্রিয় অনুসন্ধান", en: "Popular Searches" },

  // General
  "general.currency": { bn: "৳", en: "৳" },
  "general.browseProducts": { bn: "পণ্য দেখুন", en: "Browse Products" },
  "general.home": { bn: "হোম", en: "Home" },
  "general.viewAll": { bn: "সব দেখুন", en: "View All" },
  "general.loading": { bn: "লোড হচ্ছে...", en: "Loading..." },
  "general.colors": { bn: "রঙসমূহ", en: "Colors" },
  "general.viewDetails": { bn: "বিস্তারিত দেখুন", en: "View Details" },
  "general.filters": { bn: "ফিল্টার", en: "Filters" },
  "general.showResults": { bn: "ফলাফল দেখুন", en: "Show Results" },
  "general.clearFilters": { bn: "সব ফিল্টার মুছুন", en: "Clear All Filters" },
  "general.clearSearch": { bn: "সার্চ মুছুন", en: "Clear Search" },
  "general.save": { bn: "সংরক্ষণ করুন", en: "Save" },
  "general.delete": { bn: "মুছুন", en: "Delete" },
  "general.edit": { bn: "সম্পাদনা", en: "Edit" },
  "general.cancel": { bn: "বাতিল", en: "Cancel" },
  "general.back": { bn: "পিছনে", en: "Back" },
  "general.total": { bn: "মোট", en: "Total" },
  "general.qty": { bn: "পরিমাণ", en: "Qty" },
  "general.date": { bn: "তারিখ", en: "Date" },
  "general.order": { bn: "অর্ডার", en: "Order" },
  "general.track": { bn: "ট্র্যাক", en: "Track" },
  "general.download": { bn: "ডাউনলোড", en: "Download" },
  "general.invoice": { bn: "ইনভয়েস", en: "Invoice" },
  "general.items": { bn: "আইটেমসমূহ", en: "items" },
  "general.noResults": { bn: "কোনো ফলাফল পাওয়া যায়নি", en: "No results found" },

  // Orders page
  "orders.title": { bn: "আমার অর্ডার", en: "My Orders" },
  "orders.empty": { bn: "এখনো কোনো অর্ডার নেই", en: "No orders yet" },
  "orders.emptyDesc": { bn: "কেনাকাটা শুরু করুন এবং এখানে আপনার অর্ডার দেখুন।", en: "Start shopping to see your orders here." },
  "orders.startShopping": { bn: "কেনাকাটা শুরু করুন", en: "Start Shopping" },

  // Dashboard
  "dash.welcome": { bn: "SHAHEB এ স্বাগতম", en: "Welcome to SHAHEB" },
  "dash.subtitle": { bn: "আপনার ব্যক্তিগত স্টাইল ড্যাশবোর্ড", en: "Your personal style dashboard" },
  "dash.trackOrder": { bn: "অর্ডার ট্র্যাক", en: "Track Order" },
  "dash.overview": { bn: "সারসংক্ষেপ", en: "Overview" },
  "dash.myOrders": { bn: "আমার অর্ডার", en: "My Orders" },
  "dash.savedDesigns": { bn: "সংরক্ষিত ডিজাইন", en: "Saved Designs" },
  "dash.appointments": { bn: "অ্যাপয়েন্টমেন্ট", en: "Appointments" },
  "dash.aiStylist": { bn: "AI স্টাইলিস্ট", en: "AI Stylist" },
  "dash.wishlist": { bn: "উইশলিস্ট", en: "Wishlist" },
  "dash.editProfile": { bn: "প্রোফাইল সম্পাদনা", en: "Edit Profile" },
  "dash.settings": { bn: "সেটিংস", en: "Settings" },
  "dash.signOut": { bn: "সাইন আউট", en: "Sign Out" },
  "dash.totalOrders": { bn: "মোট অর্ডার", en: "Total Orders" },
  "dash.totalSpent": { bn: "মোট খরচ", en: "Total Spent" },
  "dash.recentOrders": { bn: "সাম্প্রতিক অর্ডার", en: "Recent Orders" },
  "dash.aiStyleAdvisor": { bn: "AI স্টাইল উপদেষ্টা", en: "AI Style Advisor" },
  "dash.aiStyleDesc": { bn: "ব্যক্তিগত সুপারিশ পান", en: "Get personalized recommendations" },
  "dash.savedDesignsDesc": { bn: "আপনার কাস্টম ডিজাইন আইডিয়া দেখুন", en: "View your custom design ideas" },
  "dash.bookAppointment": { bn: "অ্যাপয়েন্টমেন্ট নিন", en: "Book Appointment" },
  "dash.bookAppointmentDesc": { bn: "স্টাইলিং পরামর্শ শিডিউল করুন", en: "Schedule a styling consultation" },
  "dash.loadingOrders": { bn: "অর্ডার লোড হচ্ছে...", en: "Loading orders..." },
  "dash.noOrders": { bn: "এখনো কোনো অর্ডার নেই।", en: "No orders yet." },
  "dash.saveNewDesign": { bn: "নতুন ডিজাইন আইডিয়া সংরক্ষণ", en: "Save a New Design Idea" },
  "dash.designName": { bn: "ডিজাইনের নাম *", en: "Design Name *" },
  "dash.fabric": { bn: "কাপড়", en: "Fabric" },
  "dash.colorPalette": { bn: "রঙের প্যালেট", en: "Color Palette" },
  "dash.style": { bn: "স্টাইল", en: "Style" },
  "dash.notes": { bn: "নোট", en: "Notes" },
  "dash.saveDesign": { bn: "ডিজাইন সংরক্ষণ", en: "Save Design" },
  "dash.noDesigns": { bn: "এখনো কোনো সংরক্ষিত ডিজাইন নেই। উপরে আপনার প্রথম ডিজাইন আইডিয়া তৈরি করুন!", en: "No saved designs yet. Create your first design idea above!" },
  "dash.bookConsultation": { bn: "পরামর্শ নিন", en: "Book a Consultation" },
  "dash.yourName": { bn: "আপনার নাম *", en: "Your Name *" },
  "dash.email": { bn: "ইমেইল", en: "Email" },
  "dash.phone": { bn: "ফোন", en: "Phone" },
  "dash.type": { bn: "ধরন", en: "Type" },
  "dash.styleConsultation": { bn: "স্টাইল পরামর্শ", en: "Style Consultation" },
  "dash.customFitting": { bn: "কাস্টম ফিটিং", en: "Custom Fitting" },
  "dash.alteration": { bn: "অল্টারেশন", en: "Alteration" },
  "dash.customDesign": { bn: "কাস্টম ডিজাইন", en: "Custom Design" },
  "dash.preferredDate": { bn: "পছন্দের তারিখ *", en: "Preferred Date *" },
  "dash.preferredTime": { bn: "পছন্দের সময় *", en: "Preferred Time *" },
  "dash.selectTime": { bn: "সময় নির্বাচন করুন", en: "Select time" },
  "dash.yourAppointments": { bn: "আপনার অ্যাপয়েন্টমেন্টসমূহ", en: "Your Appointments" },
  "dash.wishlistComingSoon": { bn: "উইশলিস্ট শীঘ্রই আসছে।", en: "Wishlist feature coming soon." },
  "dash.firstName": { bn: "নাম", en: "First Name" },
  "dash.lastName": { bn: "পদবি", en: "Last Name" },
  "dash.emailAddress": { bn: "ইমেইল ঠিকানা", en: "Email Address" },
  "dash.phoneNumber": { bn: "ফোন নম্বর", en: "Phone Number" },
  "dash.changePhoto": { bn: "ছবি পরিবর্তন", en: "Change Photo" },
  "dash.saveChanges": { bn: "পরিবর্তন সংরক্ষণ", en: "Save Changes" },
  "dash.profileUpdated": { bn: "প্রোফাইল আপডেট হয়েছে!", en: "Profile updated!" },
  "dash.accountSettings": { bn: "অ্যাকাউন্ট সেটিংস", en: "Account Settings" },
  "dash.notifications": { bn: "বিজ্ঞপ্তি", en: "Notifications" },
  "dash.orderStatusUpdates": { bn: "অর্ডার স্ট্যাটাস আপডেট", en: "Order status updates" },
  "dash.orderStatusDesc": { bn: "আপনার অর্ডার শিপ বা ডেলিভার হলে জানান", en: "Get notified when your order ships or is delivered" },
  "dash.promotions": { bn: "প্রমোশন ও ডিল", en: "Promotions & deals" },
  "dash.promotionsDesc": { bn: "এক্সক্লুসিভ অফার ও ডিসকাউন্ট পান", en: "Receive exclusive offers and discounts" },
  "dash.newArrivals": { bn: "নতুন পণ্য", en: "New arrivals" },
  "dash.newArrivalsDesc": { bn: "নতুন পণ্য সম্পর্কে প্রথমে জানুন", en: "Be the first to know about new products" },
  "dash.deleteAccount": { bn: "অ্যাকাউন্ট মুছুন", en: "Delete Account" },
  "dash.viewAll": { bn: "সব দেখুন", en: "View All" },
  "dash.startShopping": { bn: "শপিং শুরু করুন", en: "Start Shopping" },
  "dash.invoice": { bn: "ইনভয়েস", en: "Invoice" },
  "dash.track": { bn: "ট্র্যাক", en: "Track" },
  "dash.browseProducts": { bn: "পণ্য দেখুন", en: "Browse Products" },
  "dash.describeVision": { bn: "আপনার ভিশন বর্ণনা করুন...", en: "Describe your vision..." },
  "dash.designSaved": { bn: "ডিজাইন সেভ হয়েছে!", en: "Design saved!" },
  "dash.designRemoved": { bn: "ডিজাইন মুছে ফেলা হয়েছে", en: "Design removed" },
  "dash.appointmentBooked": { bn: "অ্যাপয়েন্টমেন্ট বুক হয়েছে!", en: "Appointment booked!" },
  "dash.fillRequired": { bn: "দয়া করে প্রয়োজনীয় তথ্য পূরণ করুন", en: "Please fill required fields" },

  // Admin access
  "admin.loadingTitle": { bn: "অ্যাডমিন অ্যাক্সেস যাচাই হচ্ছে", en: "Checking admin access" },
  "admin.loadingDesc": { bn: "অনুগ্রহ করে অপেক্ষা করুন, আপনার অনুমতি যাচাই করা হচ্ছে।", en: "Please wait while we verify your permissions." },
  "admin.accessDeniedTitle": { bn: "অ্যাক্সেস সীমাবদ্ধ", en: "Access restricted" },
  "admin.accessDeniedDesc": { bn: "এই ড্যাশবোর্ড শুধুমাত্র admin role থাকা ইউজারদের জন্য।", en: "This dashboard is only available to users with the admin role." },
  "admin.backToDashboard": { bn: "ব্যবহারকারী ড্যাশবোর্ডে ফিরে যান", en: "Back to dashboard" },
  // AI Style
  "ai.title": { bn: "AI স্টাইল উপদেষ্টা", en: "AI Style Advisor" },
  "ai.desc": { bn: "ব্যক্তিগত কাপড়, রঙ ও স্টাইল সুপারিশ পান", en: "Get personalized fabric, color & style recommendations" },
  "ai.bodyType": { bn: "শরীরের ধরন", en: "Body Type" },
  "ai.selectBodyType": { bn: "শরীরের ধরন নির্বাচন", en: "Select body type" },
  "ai.slim": { bn: "পাতলা / চিকন", en: "Slim / Lean" },
  "ai.athletic": { bn: "অ্যাথলেটিক / পেশীবহুল", en: "Athletic / Muscular" },
  "ai.average": { bn: "গড় / মাঝারি", en: "Average / Medium" },
  "ai.broad": { bn: "প্রশস্ত / ভারী", en: "Broad / Stocky" },
  "ai.tallSlim": { bn: "লম্বা ও পাতলা", en: "Tall & Slim" },
  "ai.plus": { bn: "প্লাস সাইজ", en: "Plus Size" },
  "ai.occasion": { bn: "উপলক্ষ", en: "Occasion" },
  "ai.occasionPlaceholder": { bn: "উপলক্ষ কী?", en: "What's the occasion?" },
  "ai.casual": { bn: "ক্যাজুয়াল / প্রতিদিনের", en: "Casual / Everyday" },
  "ai.formal": { bn: "ফর্মাল / ব্যবসায়িক", en: "Formal / Business" },
  "ai.wedding": { bn: "বিয়ে / উৎসব", en: "Wedding / Festive" },
  "ai.party": { bn: "পার্টি / রাতের বাইরে", en: "Party / Night Out" },
  "ai.dateNight": { bn: "ডেট নাইট", en: "Date Night" },
  "ai.interview": { bn: "চাকরির ইন্টারভিউ", en: "Job Interview" },
  "ai.budget": { bn: "বাজেট পরিসীমা", en: "Budget Range" },
  "ai.selectBudget": { bn: "বাজেট নির্বাচন", en: "Select budget" },
  "ai.flexible": { bn: "ফ্লেক্সিবল", en: "Flexible" },
  "ai.preferences": { bn: "স্টাইল পছন্দ", en: "Style Preferences" },
  "ai.prefPlaceholder": { bn: "যেমন: মিনিমালিস্ট, বোল্ড রঙ, ক্লাসিক...", en: "e.g. minimalist, bold colors, classic..." },
  "ai.getRecommendations": { bn: "AI সুপারিশ পান", en: "Get AI Recommendations" },
  "ai.generating": { bn: "তৈরি হচ্ছে...", en: "Generating..." },
  "ai.recommendations": { bn: "AI সুপারিশ", en: "AI Recommendations" },

  // Profile page
  "profile.title": { bn: "প্রোফাইল", en: "Profile" },
  "profile.orders": { bn: "অর্ডার", en: "Orders" },
  "profile.wishlist": { bn: "উইশলিস্ট", en: "Wishlist" },
  "profile.settings": { bn: "সেটিংস", en: "Settings" },
  "profile.firstName": { bn: "নাম", en: "First Name" },
  "profile.lastName": { bn: "পদবি", en: "Last Name" },
  "profile.email": { bn: "ইমেইল", en: "Email" },
  "profile.phone": { bn: "ফোন", en: "Phone" },
  "profile.saveChanges": { bn: "পরিবর্তন সংরক্ষণ", en: "Save Changes" },
  "profile.changePassword": { bn: "পাসওয়ার্ড পরিবর্তন", en: "Change Password" },
  "profile.currentPassword": { bn: "বর্তমান পাসওয়ার্ড", en: "Current Password" },
  "profile.newPassword": { bn: "নতুন পাসওয়ার্ড", en: "New Password" },
  "profile.updatePassword": { bn: "পাসওয়ার্ড আপডেট", en: "Update Password" },
  "profile.recentOrders": { bn: "আপনার সাম্প্রতিক অর্ডার:", en: "Your recent orders:" },
  "profile.viewAllOrders": { bn: "সকল অর্ডার দেখুন", en: "View All Orders" },
  "profile.wishlistEmpty": { bn: "আপনার উইশলিস্ট খালি।", en: "Your wishlist is empty." },
  "profile.preferences": { bn: "পছন্দসমূহ", en: "Preferences" },
  "profile.preferencesDesc": { bn: "নোটিফিকেশন ও ডিসপ্লে পছন্দ শীঘ্রই আসছে।", en: "Notification and display preferences coming soon." },
  "profile.signOut": { bn: "সাইন আউট", en: "Sign Out" },

  // FAQ page
  "faq.heroTitle": { bn: "আমরা কিভাবে সাহায্য করতে পারি?", en: "How can we help you?" },
  "faq.heroDesc": { bn: "অর্ডার, পেমেন্ট, রিটার্ন ও আরো অনেক বিষয়ে সাধারণ প্রশ্নের উত্তর খুঁজুন।", en: "Find answers to common questions about orders, payments, returns, and more." },
  "faq.searchPlaceholder": { bn: "উত্তর খুঁজুন...", en: "Search for answers..." },
  "faq.resultsFor": { bn: "ফলাফল পাওয়া গেছে", en: "result(s) found for" },
  "faq.allTopics": { bn: "সকল বিষয়", en: "All Topics" },
  "faq.ordersShipping": { bn: "অর্ডার ও শিপিং", en: "Orders & Shipping" },
  "faq.paymentsTitle": { bn: "পেমেন্ট ও মূল্য", en: "Payments & Pricing" },
  "faq.returnsTitle": { bn: "রিটার্ন ও রিফান্ড", en: "Returns & Refunds" },
  "faq.digitalTitle": { bn: "ডিজিটাল পণ্য", en: "Digital Products" },
  "faq.accountTitle": { bn: "অ্যাকাউন্ট ও নিরাপত্তা", en: "Account & Security" },
  "faq.questions": { bn: "প্রশ্ন", en: "question(s)" },
  "faq.noResults": { bn: "কোনো ফলাফল পাওয়া যায়নি", en: "No results found" },
  "faq.noResultsDesc": { bn: "আমরা কোনো FAQ খুঁজে পাইনি। ভিন্ন শব্দ ব্যবহার করুন বা সব বিষয় ব্রাউজ করুন।", en: "We couldn't find any FAQ matching your search. Try different keywords or browse all topics." },
  "faq.stillQuestions": { bn: "এখনো প্রশ্ন আছে?", en: "Still have questions?" },
  "faq.stillQuestionsDesc": { bn: "যা খুঁজছেন তা পাচ্ছেন না? আমাদের সাপোর্ট টিম সপ্তাহে ৭ দিন আপনাকে সাহায্য করতে প্রস্তুত।", en: "Can't find what you're looking for? Our support team is here to help you 7 days a week." },
  "faq.contactSupport": { bn: "সাপোর্টে যোগাযোগ", en: "Contact Support" },
  "faq.trackOrder": { bn: "অর্ডার ট্র্যাক", en: "Track Order" },
  "faq.checkStatus": { bn: "আপনার অর্ডার স্ট্যাটাস দেখুন", en: "Check your order status" },
  "faq.returns": { bn: "রিটার্ন", en: "Returns" },
  "faq.startReturn": { bn: "রিটার্ন বা এক্সচেঞ্জ শুরু করুন", en: "Start a return or exchange" },
  "faq.myAccount": { bn: "আমার অ্যাকাউন্ট", en: "My Account" },
  "faq.manageProfile": { bn: "আপনার প্রোফাইল পরিচালনা করুন", en: "Manage your profile" },

  // Track Order
  "track.title": { bn: "আপনার অর্ডার ট্র্যাক করুন", en: "Track Your Order" },
  "track.desc": { bn: "আপনার অর্ডার আইডি দিন এবং রিয়েল-টাইম স্ট্যাটাস দেখুন।", en: "Enter your order ID to see real-time status updates." },
  "track.placeholder": { bn: "অর্ডার আইডি দিন (যেমন ORD-2026-001)", en: "Enter Order ID (e.g., ORD-2026-001)" },
  "track.button": { bn: "ট্র্যাক", en: "Track" },
  "track.orderId": { bn: "অর্ডার আইডি", en: "Order ID" },
  "track.inTransit": { bn: "পথে আছে", en: "In Transit" },
  "track.orderPlaced": { bn: "অর্ডার করা হয়েছে", en: "Order Placed" },
  "track.paymentConfirmed": { bn: "পেমেন্ট নিশ্চিত", en: "Payment Confirmed" },
  "track.shipped": { bn: "শিপ করা হয়েছে", en: "Shipped" },
  "track.outForDelivery": { bn: "ডেলিভারির জন্য বের হয়েছে", en: "Out for Delivery" },
  "track.delivered": { bn: "ডেলিভারি হয়েছে", en: "Delivered" },
  "track.expected": { bn: "আনুমানিক", en: "Expected" },
  "track.shippingAddress": { bn: "শিপিং ঠিকানা", en: "Shipping Address" },
  "track.carrier": { bn: "কুরিয়ার", en: "Carrier" },

  // About page
  "about.title": { bn: "SHAHEB সম্পর্কে", en: "About SHAHEB" },
  "about.subtitle": { bn: "পুরুষদের ফ্যাশনের প্রতি ভালোবাসা থেকে জন্ম, SHAHEB ঐতিহ্য ও আধুনিকতার মধ্যে সেতু তৈরি করে।", en: "Born from a love of men's fashion, SHAHEB bridges tradition and modernity." },
  "about.ourStory": { bn: "আমাদের গল্প", en: "Our Story" },
  "about.storyP1": { bn: "SHAHEB ২০২৪ সালে একটি সহজ দৃষ্টিভঙ্গি নিয়ে প্রতিষ্ঠিত হয়েছিল — প্রিমিয়াম, সুনিপুণভাবে তৈরি পুরুষদের ফ্যাশন সবার কাছে সহজলভ্য করা। আমরা বিশ্বাস করি প্রতিটি পুরুষ আত্মবিশ্বাসী ও স্টাইলিশ অনুভব করার যোগ্য, সেটা বোর্ডরুম মিটিং হোক, উৎসব উদযাপন হোক, বা প্রতিদিনের বাইরে যাওয়া হোক।", en: "SHAHEB was founded in 2024 with a simple vision — making premium, expertly crafted men's fashion accessible to everyone. We believe every man deserves to feel confident and stylish, whether it's a boardroom meeting, a festive celebration, or an everyday outing." },
  "about.storyP2": { bn: "হাতে বাছাই করা এথনিক পোশাক থেকে আধুনিক স্ট্রিট স্টাইল এবং এক্সক্লুসিভ ডিজিটাল স্টাইল গাইড, আমরা এমন পণ্য সংগ্রহ করি যা সমসাময়িক বাংলাদেশী পুরুষকে উদযাপন করে। মান, প্রামাণিকতা এবং গ্রাহক অভিজ্ঞতা আমাদের সবকিছুর কেন্দ্রে।", en: "From hand-picked ethnic wear to modern street style and exclusive digital style guides, we curate products that celebrate the contemporary Bangladeshi man. Quality, authenticity, and customer experience are at the heart of everything we do." },
  "about.happyCustomers": { bn: "সন্তুষ্ট গ্রাহক", en: "Happy Customers" },
  "about.products": { bn: "পণ্যসমূহ", en: "Products" },
  "about.deliveryDistricts": { bn: "জেলায় ডেলিভারি", en: "Districts Delivery" },
  "about.customerRating": { bn: "গ্রাহক রেটিং", en: "Customer Rating" },

  // Contact page
  "contact.getInTouch": { bn: "যোগাযোগ করুন", en: "Get in Touch" },
  "contact.title": { bn: "আমাদের সাথে যোগাযোগ", en: "Contact Us" },
  "contact.subtitle": { bn: "কোনো প্রশ্ন, সাহায্যের দরকার, বা শুধু হ্যালো বলতে চান? আমরা আপনার কথা শুনতে চাই।", en: "Have a question, need help, or just want to say hello? We'd love to hear from you." },
  "contact.orderIssue": { bn: "অর্ডার সমস্যা", en: "Order Issues" },
  "contact.trackReport": { bn: "ট্র্যাক বা রিপোর্ট", en: "Track or Report" },
  "contact.inquiries": { bn: "জিজ্ঞাসা", en: "Inquiries" },
  "contact.generalQuestions": { bn: "সাধারণ প্রশ্ন", en: "General Questions" },
  "contact.liveChat": { bn: "লাইভ চ্যাট", en: "Live Chat" },
  "contact.chatWithUs": { bn: "আমাদের সাথে চ্যাট করুন", en: "Chat with us" },
  "contact.callUs": { bn: "কল করুন", en: "Call Us" },
  "contact.contactInfo": { bn: "যোগাযোগের তথ্য", en: "Contact Info" },
  "contact.emailLabel": { bn: "ইমেইল", en: "Email" },
  "contact.emailReply": { bn: "২৪ ঘণ্টার মধ্যে উত্তর দিই", en: "We reply within 24 hours" },
  "contact.phoneLabel": { bn: "ফোন", en: "Phone" },
  "contact.phoneHours": { bn: "শনি-বৃহঃ, সকাল ১০টা - রাত ৮টা", en: "Sat-Thu, 10 AM - 8 PM" },
  "contact.addressLabel": { bn: "ঠিকানা", en: "Address" },
  "contact.workingHours": { bn: "কর্মসময়", en: "Working Hours" },
  "contact.closedDays": { bn: "শুক্রবার ও সরকারি ছুটিতে বন্ধ", en: "Closed on Fridays & public holidays" },
  "contact.mapComingSoon": { bn: "ম্যাপ ভিউ শীঘ্রই আসছে", en: "Map view coming soon" },
  "contact.sendMessage": { bn: "আমাদের বার্তা পাঠান", en: "Send us a Message" },
  "contact.fullName": { bn: "পুরো নাম *", en: "Full Name *" },
  "contact.emailRequired": { bn: "ইমেইল *", en: "Email *" },
  "contact.phoneOptional": { bn: "ফোন", en: "Phone" },
  "contact.category": { bn: "বিভাগ", en: "Category" },
  "contact.selectCategory": { bn: "বিষয় নির্বাচন করুন", en: "Select a topic" },
  "contact.orderIssueOpt": { bn: "অর্ডার সমস্যা", en: "Order Issue" },
  "contact.productRelated": { bn: "পণ্য সম্পর্কিত", en: "Product Related" },
  "contact.returnRefund": { bn: "রিটার্ন / রিফান্ড", en: "Return / Refund" },
  "contact.feedback": { bn: "মতামত", en: "Feedback" },
  "contact.other": { bn: "অন্যান্য", en: "Other" },
  "contact.subject": { bn: "বিষয় *", en: "Subject *" },
  "contact.subjectPlaceholder": { bn: "কিভাবে সাহায্য করতে পারি?", en: "How can we help?" },
  "contact.message": { bn: "বার্তা *", en: "Message *" },
  "contact.messagePlaceholder": { bn: "বিস্তারিত লিখুন...", en: "Write in detail..." },
  "contact.orderIdOptional": { bn: "অর্ডার আইডি (ঐচ্ছিক)", en: "Order ID (optional)" },
  "contact.sendBtn": { bn: "বার্তা পাঠান", en: "Send Message" },
  "contact.sent": { bn: "বার্তা পাঠানো হয়েছে!", en: "Message Sent!" },
  "contact.sentDesc": { bn: "আমরা আপনার বার্তা পেয়েছি এবং ২৪ ঘণ্টার মধ্যে উত্তর দেব।", en: "We've received your message and will respond within 24 hours." },
  "contact.sendAnother": { bn: "আরেকটি বার্তা পাঠান", en: "Send Another Message" },

  // Category page
  "category.products": { bn: "টি পণ্য", en: "products" },
  "category.noProducts": { bn: "এই ক্যাটেগরিতে এখনো কোনো পণ্য নেই।", en: "No products in this category yet." },
  "category.browseAll": { bn: "সকল পণ্য দেখুন", en: "Browse All Products" },

  // Invoice
  "invoice.title": { bn: "ইনভয়েস", en: "INVOICE" },
  "invoice.item": { bn: "আইটেম", en: "Item" },
  "invoice.price": { bn: "মূল্য", en: "Price" },
  "invoice.subtotal": { bn: "সাবটোটাল", en: "Subtotal" },
  "invoice.gst": { bn: "GST (১৮%)", en: "GST (18%)" },
  "invoice.downloadPdf": { bn: "PDF ডাউনলোড", en: "Download PDF" },
  "invoice.downloaded": { bn: "ইনভয়েস ডাউনলোড হয়েছে!", en: "Invoice downloaded!" },

} as const;

type TranslationKey = keyof typeof translations;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("shaheb_lang");
    return (saved === "en" || saved === "bn") ? saved : "bn";
  });

  useEffect(() => {
    localStorage.setItem("shaheb_lang", language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: TranslationKey): string => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
